version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=process.env.APP_DB_NAME
      - POSTGRES_USER=process.env.DATABASE_USER
      - POSTGRES_PASSWORD=process.env.DATABASE_PASSWORD
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: process.env.DATABASE_USER
      POSTGRES_DB: process.env.APP_DB_NAME
      POSTGRES_PASSWORD: process.env.DATABASE_PASSWORD
      POSTGRES_HOST: process.env.PGHOST