version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:8280"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://crypto@postgres/crypto
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: process.env.DATABASE_USER
      POSTGRES_DB: process.env.APP_DB_NAME